---
# tasks file for roles/hostname
- name: Check hostname
  become: true
  command: bash -lc "hostname"
  register: check_hostname
  changed_when: False

- name: debug
  debug:
    msg: "{{ check_hostname }}"
- name: debug
  debug:
    msg: "{{ hostname }}"

- name: before Set hostname
  become: true
  hostname:
    name: "{{ hostname }}"
  register: set_hostname
  when: check_hostname.stdout != hostname
  changed_when: False
  ignore_errors: yes

- name: Set hostname
  become: true
  hostname:
    name: "{{ hostname }}"
  when: set_hostname is false
