---
- name: softether
  hosts: softether
  roles:
    - role: common
      tags:
        - common
        - softether

    - role: ansible_user
      tags:
        - init
        - softether

    - role: sshd
      tags:
        - sshd
        - softether

    - role: hostname
      tags:
        - hostname
        - softether

    - role: users
      tags:
        - users
        - softether

    - role: firewalld
      tags:
        - firewalld
        - softether

    - role: softether
      tags:
        - softether

    - role: bash_it
      tags:
        - bash_it
        - tools

