---
#  Firewalld vars
 firewalld_service:
 - service: 'ssh'
   zone: 'public'
   permanent: 'yes'
   state: 'enabled'
   immediate: true
 - service: 'ipsec'
   zone: 'public'
   permanent: 'yes'
   state: 'enabled'
   immediate: true
 - service: 'openvpn'
   zone: 'public'
   permanent: 'yes'
   state: 'enabled'
   immediate: true

 firewalld_ports:
   - port: "{{ softether_openvpn_portsoftether_openvpn_port }}/tcp"
     permanent: "yes"
     state: "enabled"
   - port: "{{ sshd_port }}/tcp"
     permanent: "yes"
     state: "enabled"
