---
# tasks file for common
- name: Time zone
  become: True
  shell: "timedatectl | grep 'Time zone' | awk '{print  $3}'"
  register: time_zone
  changed_when: False
  ignore_errors: yes

- name: Install Tmezone
  become: true
  shell: |
    timedatectl set-timezone "{{ os_time_zone }}"
  when:
    - time_zone.stdout != os_time_zone

- name: yum fasterstmirror
  lineinfile:
    path: '/etc/yum/pluginconf.d/fastestmirror.conf'
    line: "enabled=1"
    state: present
    regexp: "^#?enabled="
    insertafter: EOF
    create: yes
    owner: root
    group: root
    mode: 0644

- name: yum fasterstmirror
  blockinfile:
    path: '/etc/yum/pluginconf.d/fastestmirror.conf'
    block: |
      prefer=ftp.jaist.ac.jp
      verbose=1
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644


- name: install epel
  become: true
  yum:
    name: epel-release
    state: installed

- name: yum update
  become: true
  yum:
    name: '*'
    # state: latest
    # update_cache: yes

- name: install development tools
  become: true
  yum:
    name: "@Development tools"
    state: present
    skip_broken: true